### ISSUE TITLE
Scrollbar location

### ISSUE THREAD

**Issue by bdch1234** [jtpio/retrolab#130]
It is just a minor detail really, but personally I kind of liked how the scrollbar used to appear to the far right in the classic notebook:
![image](https://user-images.githubusercontent.com/46796385/119161492-aa7b6000-ba59-11eb-9bd1-28df2dfc2797.png)

RetroLab:
![image](https://user-images.githubusercontent.com/46796385/119161697-e7dfed80-ba59-11eb-87fd-9ea92a294525.png)

Don't know if this would be difficult to do here though.

**Comment by jtpio** [comment]
Thanks @bdch1234.

It would indeed be better to have the scrollbar apply to the whole page.

I think this was discussed in https://github.com/jtpio/retrolab/issues/63 before. Would you like to move the conversation there?

**Comment by bdch1234** [comment]
Sure thing, closing this as a dupe

**Comment by bdch1234** [comment]
@jtpio, really love this addition to jupyterlab by the way!
